//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        public UserInformation()
        {
            this.PoleInfoes = new HashSet<PoleInfo>();
            this.PoleInfoes1 = new HashSet<PoleInfo>();
            this.PoleTypes = new HashSet<PoleType>();
        }
    
        public int Id { get; set; }
        public string AspNetUserId { get; set; }
        public string AspNetRoleID { get; set; }
        public string UserFullName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UPassword { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<PoleInfo> PoleInfoes { get; set; }
        public virtual ICollection<PoleInfo> PoleInfoes1 { get; set; }
        public virtual ICollection<PoleType> PoleTypes { get; set; }
    }
}
