//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoleImage
    {
        public long ID { get; set; }
        public Nullable<int> PoleInfoID { get; set; }
        public string ImageMapPath { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual PoleInfo PoleInfo { get; set; }
        public virtual UserInformation UserInformation { get; set; }
    }
}
